/*================================================================
AUTOMATED PATH UPDATE INSTRUCTION
================================================================
NEW ROOT DIRECTORY FOR COMPONENT:
FACILITYS_TRACKER_APP/views/view_3_contacts/view_3_grid_components/

ACTION REQUIRED BY AI:
1. Scan this file for any import statements or paths pointing to 'view_3_grid.js'.
2. Update those paths so they correctly target the new folder and split files:
   - view_3_grid.js
   - view_3_grid_logic.js
3. Ensure all other local relative paths (../) are mathematically adjusted 
   to account for the deeper directory depth of the new folder level.
4. Run the LINE COUNT AUDIT before writing code.
================================================================*/ /*================================================================
FILE METADATA
================================================================
FILE NAME    : view_3_data.js
SUPABASE TBL : contacts
VIEW NAME    : Add New Facility
POP-UP TITLE : Create Directory Entry
LAST UPDATED : 2026-06-06 @ 05:18 PM
================================================================
AI CODING RULES & CONSTRAINTS (Read before making any changes)
================================================================
1. STRICT ADHERENCE: Always follow these rules without exception.

2. MISSING METADATA HANDLING: If any fields in the FILE METADATA 
   section above are generic placeholders or missing, the AI must 
   immediately read the provided source code below to determine the 
   correct tables/views/titles. CRITICAL FOR FILE NAME: Look strictly 
   at the user's prompt text or comments for the exact sequential 
   filename (e.g., view_2_data.js). NEVER invent, guess, or substitute 
   a descriptive semantic name (like facility_data_service.js) based 
   on the code context. If the exact filename cannot be verified, 
   leave the placeholder intact or ask the user.

3. NO UNSANCTIONED CHANGES: Never change, remove, or modify any rules 
   in this header unless explicitly asked by the user.

4. SCOPE OF WORK: Only modify the specific functions, lines, or 
   features requested in the prompt.

5. PRESERVATION: Do NOT refactor, rename, or optimize any other 
   part of the code. Leave all working logic exactly as it is.

6. LOGGING CHANGES: If a variable name or structure must change to 
   make a fix work, explicitly state *why* in the text response 
   before showing the code.

7. CODE COMPLETENESS: Provide the full updated function or file so 
   nothing gets accidentally lost in translation.

8. VIEW IDENTIFIERS: Ensure the view/pop-up has a visible UI tag 
   identifying its source file, last update date, and time. If missing, 
   add it to the UI layout. Update this tag on every modification.

9. NO BLIND CODE: Never create a new file or assume the contents of 
   an existing file unless the current code is fully pasted into 
   the prompt. If missing, stop and ask for it.

10. UNIQUE ALERTS: Never use generic default message boxes for custom 
    notifications. Always add a distinct, visible ID or tag to the 
    message box UI referencing its specific component/file.

11. CODE BLOCK DELIVERY: Always deliver the entire updated file, 
    including this header and all rules, wrapped completely inside 
    a single markdown code block to allow for easy copying.

12. METADATA AUTO-UPDATE: On every code delivery, ensure all fields 
    in this header (File Name, Table, View, Title, Date, Time) are 
    fully updated and preserved at the top of the file.
================================================================*/
const __FILENAME = 'view_3_data.js';
import { supabase } from '../../js/supabaseClient.js';

/**
 * Uploads a raw camera image file directly to the Supabase storage bucket.
 * @param {File} file - The image file generated by the camera capture interface.
 * @returns {Promise<string|null>} The public URL string of the asset, or null if failed.
 */
export async function uploadContactImage(file) {
    try {
        if (!file) return null;

        // Generate a clean unique filename to avoid collisions
        const fileExt = file.name ? file.name.split('.').pop() : 'jpg';
        const fileName = `${Date.now()}_${Math.random().toString(36).substring(2, 7)}.${fileExt}`;
        const filePath = `contact-avatars/${fileName}`;

        // Upload to a storage bucket named 'contacts'
        const { data, error } = await supabase.storage
            .from('contacts')
            .upload(filePath, file);

        if (error) {
            console.error("Error uploading camera binary to storage:", error.message);
            return null;
        }

        // Retrieve and return the public web accessible asset URL
        const { data: publicUrlData } = supabase.storage
            .from('contacts')
            .getPublicUrl(filePath);

        return publicUrlData?.publicUrl || null;
    } catch (err) {
        console.error("Unexpected operational failure inside uploadContactImage:", err);
        return null;
    }
}

/**
 * Fetches all active contact directory records associated with a specific facility.
 * @param {string|number} facilityId - The database primary key of the facility.
 * @returns {Promise<Array>} List of contact entry objects.
 */
export async function fetchContacts(facilityId) {
    try {
        if (!facilityId) return [];
        
        const { data, error } = await supabase
            .from('contacts')
            .select('*')
            .eq('facility_id', Number(facilityId))
            .order('contact_name', { ascending: true });

        if (error) {
            console.error("Error fetching facility contacts:", error.message);
            return [];
        }
        return data || [];
    } catch (err) {
        console.error("Unexpected error in fetchContacts operational runtime:", err);
        return [];
    }
}

/**
 * Persists a new contact record inside the database directory schema.
 * @param {Object} contactPayload - The complete structured payload details of the contact.
 * @returns {Promise<Object|null>} The newly instantiated database row data or null if failed.
 */
export async function insertContact(contactPayload) {
    try {
        const normalizedPayload = { ...contactPayload };
        if ('name' in normalizedPayload) {
            normalizedPayload.contact_name = normalizedPayload.name;
            delete normalizedPayload.name;
        }

        const { data, error } = await supabase
            .from('contacts')
            .insert([normalizedPayload])
            .select();

        if (error) {
            console.error("Error inserting directory contact payload:", error.message);
            return null;
        }
        return data && data.length > 0 ? data[0] : null;
    } catch (err) {
        console.error("Unexpected system exception inside insertContact context:", err);
        return null;
    }
}

/**
 * Updates an existing directory profile entry record mapping against its unique reference key.
 * @param {string|number} contactId - The primary key ID of the target contact record.
 * @param {Object} updatePayload - Structured payload containing the revised values.
 * @returns {Promise<Object|null>} The updated row data returned from the database layer or null.
 */
export async function updateContact(contactId, updatePayload) {
    try {
        if (!contactId) return null;

        const normalizedPayload = { ...updatePayload };
        if ('name' in normalizedPayload) {
            normalizedPayload.contact_name = normalizedPayload.name;
            delete normalizedPayload.name;
        }

        const { data, error } = await supabase
            .from('contacts')
            .update(normalizedPayload)
            .eq('id', contactId)
            .select();

        if (error) {
            console.error("Error patching directory contact payload row:", error.message);
            return null;
        }
        return data && data.length > 0 ? data[0] : null;
    } catch (err) {
        console.error("Unexpected system exception inside updateContact context:", err);
        return null;
    }
}

/**
 * Completely removes a directory profile row out of the target schema database tables.
 * @param {string|number} contactId - The primary key ID of the targeted contact record.
 * @returns {Promise<boolean>} True if the row row entry was dropped successfully, otherwise false.
 */
export async function deleteContact(contactId) {
    try {
        if (!contactId) return false;

        const { error } = await supabase
            .from('contacts')
            .delete()
            .eq('id', contactId);

        if (error) {
            console.error("Error performing delete contact operation reference:", error.message);
            return false;
        }
        return true;
    } catch (err) {
        console.error("Unexpected system exception inside deleteContact context:", err);
        return false;
    }
}
